export const FETCH_APP_RECOMMEND_REQUEST = "FETCH_APP_RECOMMEND_REQUEST";
export const FETCH_APP_RECOMMEND_SUCCESS = "FETCH_APP_RECOMMEND_SUCCESS";
export const FETCH_APP_RECOMMEND_FAILURE = "FETCH_APP_RECOMMEND_FAILURE";