export const FETCH_APP_RECOMMEND_START = "FETCH_APP_RECOMMEND_START";
export const FETCH_APP_RECOMMEND_SUCCESS = "FETCH_APP_RECOMMEND_SUCCESS";
export const FETCH_APP_RECOMMEND_FAILURE = "FETCH_APP_RECOMMEND_FAILURE";

export const UPDATE_APP_RECOMMEND = "UPDATE_APP_RECOMMEND";
