export const FETCH_APP_RECOMMEND_START = "FETCH_APP_RECOMMEND_START";
export const FETCH_APP_RECOMMEND_SUCCESS = "FETCH_APP_RECOMMEND_SUCCESS";
export const FETCH_APP_RECOMMEND_FAILURE = "FETCH_APP_RECOMMEND_FAILURE";

export const UPDATE_APP_RECOMMEND = "UPDATE_APP_RECOMMEND";
export const UPDATE_APP_RECOMMEND_FILTERED = "UPDATE_APP_RECOMMEND_FILTERED";
export const APP_RECOMMEND_FILTER_APP = "APP_RECOMMEND_FILTER_APP";
