export const FETCH_APP_LISTING_START = "FETCH_APP_LISTING_START";
export const FETCH_APP_LISTING_SUCCESS = "FETCH_APP_LISTING_SUCCESS";
export const FETCH_APP_LISTING_FAILURE = "FETCH_APP_LISTING_FAILURE";