export const FETCH_APP_LISTING_START = "FETCH_APP_LISTING_START";
export const FETCH_APP_LISTING_SUCCESS = "FETCH_APP_LISTING_SUCCESS";
export const FETCH_APP_LISTING_FAILURE = "FETCH_APP_LISTING_FAILURE";

export const UPDATE_APP_LISTING = "UPDATE_APP_LISTING";

export const SET_APP_LISTING_PAGE = "SET_APP_LISTING_PAGE";
export const SET_APP_LISTING_LOADED_PAGES = "SET_APP_LISTING_LOADED_PAGES";